networks:
  graylog:
    external: true

secrets:
  traefik.certificate:
    file: ./secrets/traefik/graylog.sopaline.lan.crt
  traefik.key:
    file: ./secrets/traefik/graylog.sopaline.lan.key

services:
  reverse-proxy:
    image: traefik:3.2.0
    command:
      - --providers.file.directory=/config
      - --providers.docker
      - --entryPoints.web.address=:80
      - --entryPoints.websecure.address=:443
      - --entrypoints.websecure.http.tls=true
    networks:
      - graylog
    ports:
      - 443:443/tcp
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config/traefik:/config:ro
    secrets:
      - source: traefik.certificate
        target: /certs/graylog.sopaline.lan.crt
      - source: traefik.key
        target: /certs/graylog.sopaline.lan.key